apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtyu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtyu
  template:
    metadata:
      labels:
        app: rtyu
    spec:
      containers:
      - image: okteto.dev/rtyu:latest
        name: rtyu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "cf62d96b-c381-46cb-8945-7cfd1ff8f072"
        - name: Vless_Path
          value: "/vljhg555"
        - name: Vmess_UUID
          value: "cf62d96b-c381-46cb-8945-7cfd1ff8f072"
        - name: Vmess_Path
          value: "/vm66kj6"
        - name: Share_Path
          value: "/v2link"
